import Providers from "./providers";
import Header from "./components/Header";

export const metadata = {
  title: "World Tour",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
